---
id: rubykaigi-2023-followup
base_name: slide
tags: ["ruby", "rubykaigi", "quic"]
presentation_date: 2023-08-19
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: ['MIT']
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri: https://github.com/unasuke/rubykaigi-2023-followup
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
